# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
[tool.black]
line-length = 88
target-version = [
    "py310",
]

[tool.isort]
line_length = 88
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",
    "ANN101",
]

[tool.pylint."FORMAT"]
max-line-length = 88

[tool.pylint."BASIC"]
good-names = [
    "x",
    "y",
    "z",
    "i",
    "j",
    "k",
]

[tool.pylint."MESSAGES CONTROL"]
# https://vald-phoenix.github.io/pylint-errors/#list-of-errors
disable = [
    "C0411",  # wrong-import-order
]
ignore-paths = [
    "pyproject.toml",
    "tests",
]

[tool.pytest]
filterwarnings = "ignore::DeprecationWarning"
